spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/coniverse_dev
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

---
# 쿠버네티스 환경 (배포 환경)
spring:
  config:
    activate:
      on-cloud-platform: kubernetes

  datasource:
    url: jdbc:mysql://34.64.100.229:3306/coniverse_dev
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

