# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI(Continuous integration)

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main, develop, feature/* ]

env:
  INSTANCE_CONNECTION_NAME: mdag-community:asia-northeast3:coniverse-dev

jobs:
  Continuous_Integration:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Up MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: 5.7
          mysql database: 'coniverse_dev'
          mysql user: 'root'
          mysql password: '1234'
          mysql root password: '1234'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Verify With Maven
        run: mvn -B verify --file pom.xml

      - name: Check TestCoverage
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: ./target/site/jacoco/jacoco.csv
          fail-if-coverage-less-than: 0.9

      - name: Build With Docker
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: false

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./target/site/jacoco/jacoco.xml

