# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI(Continuous integration)

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main, develop, feature/* ]

env:
  INSTANCE_CONNECTION_NAME: mdag-community:asia-northeast3:coniverse-dev

jobs:
  Continuous_Integration:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Setup Google Cloud CLI
      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      - run: |-
          gcloud --quiet auth configure-docker
      - name: Get Cloud SQL Proxy
        run: |
          wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
          chmod +x cloud_sql_proxy
      - name: Run Cloud SQL Proxy
        run: ./cloud_sql_proxy -instances=${{ env.INSTANCE_CONNECTION_NAME }}=tcp:127.0.0.1:3306 &

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Verify With Maven
        run: mvn -B verify --file pom.xml

      - name: Build With Docker
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: false
